version: "3.9"
services:
  app:
    build: .
    deploy:
      replicas: 1
    volumes:
      - type: bind
        source: /home/ubuntu/bots_config/config.yaml
        target: /OS_check_list/config.yaml
    network_mode: "host"
