version: "3.3"
services:
  app:
    build: .
    deploy:
      replicas: 1
    volumes:
      - type: bind
        source: /home/ubuntu/bots_config/config.yaml
        target: /OS_check_list/config.yaml
      - type: bind
        source: /var/log/os-check-list-bot/os_check_list.log
        target: /OS_check_list/logs/os_check_list.log
    network_mode: "host"
    restart: unless-stopped
